server:
  port: 8030

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: 7777
  jpa:
    hibernate:
      ddl-auto: update
