server:
  port: 8029
  
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://mysql:3306/springdb
        username: root
        password: 7777
        driver-class-name: com.mysql.jdbc.Driver
